import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowDown, ArrowRight, ArrowUpRight, Atom, BookOpen, BrainCircuit, BriefcaseBusiness, Check, ChevronDown, Code2, Copy, Download, Eye, GraduationCap, HeartPulse, Layers3, Link2, Mail, MapPin, Menu, MessageSquareText, Network, Phone, Sparkles, X } from 'lucide-react'
import { certifications, education, experience, personalInfo, projects, researchInterests, skills } from './data'

const navItems = [['Research', 'research'], ['Experience', 'experience'], ['Education', 'education'], ['Projects', 'projects'], ['Publications', 'publications'], ['Skills', 'skills'], ['Contact', 'contact']]
const appear = { hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0, transition: { duration: .42 } } }

function Tags({ items }: { items: string[] }) { return <div className="tags">{items.map(item => <span key={item}>{item}</span>)}</div> }
function SectionIntro({ number, label, title, children }: { number: string; label: string; title: string; children?: React.ReactNode }) { return <div className="section-intro"><div className="section-rule"><span>{number}</span><i /><b>{label}</b></div><h2>{title}</h2>{children && <p>{children}</p>}</div> }
function GithubMark() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 2a10 10 0 0 0-3.16 19.49c.5.09.68-.21.68-.48v-1.7c-2.78.6-3.37-1.18-3.37-1.18-.46-1.16-1.11-1.47-1.11-1.47-.91-.62.07-.61.07-.61 1 .07 1.54 1.04 1.54 1.04.9 1.53 2.35 1.09 2.92.83.09-.65.35-1.09.64-1.34-2.22-.25-4.56-1.11-4.56-4.94 0-1.09.39-1.98 1.03-2.68-.1-.25-.45-1.27.1-2.65 0 0 .84-.27 2.75 1.02A9.6 9.6 0 0 1 12 6.8a9.6 9.6 0 0 1 2.5.34c1.91-1.29 2.75-1.02 2.75-1.02.55 1.38.2 2.4.1 2.65.64.7 1.03 1.59 1.03 2.68 0 3.84-2.34 4.68-4.57 4.93.36.31.68.91.68 1.83v2.8c0 .27.18.58.69.48A10 10 0 0 0 12 2Z" /></svg> }

function Navbar() { const [open, setOpen] = useState(false); const [active, setActive] = useState('research'); useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-22% 0px -70% 0px' }); document.querySelectorAll('main section[id]').forEach(el => observer.observe(el)); return () => observer.disconnect() }, []); return <header className="nav-shell"><nav className="navbar"><a href="#home" className="brand">Abhishek<span>.</span>Singh</a><div className={open ? 'nav-menu is-open' : 'nav-menu'}>{navItems.map(([name, id]) => <a key={id} href={`#${id}`} className={active === id ? 'active' : ''} onClick={() => setOpen(false)}>{name}</a>)}</div><a className="cv-button" href={`${import.meta.env.BASE_URL}Abhishek_Research_CV.pdf`} download="Abhishek_Research_CV.pdf"><Download />CV</a><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button></nav></header> }

function Hero() { const reduced = useReducedMotion(); return <section id="home" className="hero"><div className="hero-layout"><motion.div initial={reduced ? false : 'hidden'} animate="visible" variants={{ visible: { transition: { staggerChildren: .08 } } }} className="hero-copy"><motion.p variants={appear} className="hero-kicker">// AI RESEARCH PORTFOLIO — 2026</motion.p><motion.div variants={appear} className="name-with-photo"><h1>Abhishek<br />Singh<span>.</span></h1><figure className="profile-card"><img src={`${import.meta.env.BASE_URL}abhishek-profile-research.png`} alt="Abhishek Singh" /></figure></motion.div><motion.h2 variants={appear}>AI/ML Researcher<br />&amp; Computer Science <em>Engineer</em></motion.h2><motion.p variants={appear} className="hero-specialism">Researching Deep Learning, Multimodal AI, Vision-Language Models, and Generative AI.</motion.p><motion.p variants={appear} className="hero-description">I am a computer science researcher working at the intersection of deep learning, multimodal AI, computer vision, NLP, and generative AI. My work focuses on building intelligent systems that understand, reason over, and generate information from complex multimodal data.</motion.p><motion.div variants={appear} className="hero-actions"><a href="#research" className="button fill">View Research <ArrowRight /></a><a href="#projects" className="button">Explore Projects</a><a href="/Abhishek_Research_CV.pdf" download className="button"><Download /> Download CV</a></motion.div><motion.div variants={appear} className="hero-social"><a href={personalInfo.linkedinUrl} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Link2 /></a><a href={`mailto:${personalInfo.email}`} aria-label="Email"><Mail /></a><span className="social-placeholder" title="GitHub profile URL has not been provided" aria-label="GitHub"><GithubMark /></span><i /><span>{personalInfo.location}</span></motion.div></motion.div></div></section> }
function ResearchTicker() { const topics = ['3D COMPUTER VISION', 'NEURAL RENDERING', 'GENERATIVE MODELS', 'MULTIMODAL AI', 'VISION-LANGUAGE MODELS', 'LARGE LANGUAGE MODELS']; const strip = topics.map(topic => <span key={topic}>{topic}<i>✦</i></span>); return <section className="research-ticker" aria-label="Research areas"><div className="ticker-track"><div>{strip}</div><div aria-hidden="true">{strip}</div></div></section> }

const domains = [['Multimodal AI', 'Vision-Language Models, multimodal reasoning, image-text understanding', Layers3], ['Deep Learning', 'CNNs, Transformers, GANs, transfer learning and modern neural architectures', BrainCircuit], ['Generative AI', 'LLMs, RAG, LangChain, multimodal LLMs and generative models', Sparkles], ['Computer Vision', 'Medical imaging, image understanding, 3D reconstruction and visual reasoning', Eye], ['NLP', 'Natural language processing, OCR, semantic retrieval and reasoning', MessageSquareText], ['AI for Healthcare', 'Medical imaging and intelligent diagnostic systems', HeartPulse]]
function ResearchFocus() { return <section id="research" className="section"><SectionIntro number="01" label="RESEARCH FOCUS" title="Research Focus">Core areas of investigation across multimodal intelligence, deep learning, and applied AI systems.</SectionIntro><div className="domain-grid">{domains.map(([name, text, Icon], index) => { const IconComponent = Icon as typeof Layers3; return <motion.article initial="hidden" whileInView="visible" viewport={{ once: true }} variants={{ ...appear, visible: { ...appear.visible, transition: { delay: index * .04 } } }} className="domain-card" key={name as string}><div><span className="domain-icon"><IconComponent /></span><small>0{index + 1}</small></div><h3>{name as string}</h3><p>{text as string}</p></motion.article> })}</div></section> }

function Experience() { return <section id="experience" className="section experience"><SectionIntro number="02" label="RESEARCH EXPERIENCE" title="Research Experience">Fellowships at premier Indian institutes, spanning medical imaging diagnostics and defense-funded security research.</SectionIntro><div className="timeline">{experience.map((item, index) => <motion.article initial="hidden" whileInView="visible" viewport={{ once: true }} variants={appear} className="timeline-card" key={item.short}><span className={`timeline-dot ${index === 0 ? 'current' : ''}`} /><div className="timeline-card-top"><p><BriefcaseBusiness /> {item.period} {index === 0 && <b>CURRENT</b>}</p></div><h3>{item.short}</h3><h4>{item.role}</h4><p className="timeline-description">{item.description}</p><ul>{item.highlights.slice(0, 2).map(([, detail]) => <li key={detail}>{detail}</li>)}</ul><Tags items={item.tags} /></motion.article>)}</div></section> }

function Education() { return <section id="education" className="section"><SectionIntro number="03" label="ACADEMIC BACKGROUND" title="Education">A computer science foundation culminating in a research-focused postgraduate specialization in data science.</SectionIntro><div className="education-grid">{education.map((item, index) => <article className={`degree-card ${index === 0 ? 'featured-degree' : ''}`} key={item.degree}>{index === 0 && <span className="degree-badge">RESEARCH DEGREE</span>}<div className="degree-top"><span className="degree-icon"><GraduationCap /></span><time>{item.period}</time></div><h3>{item.degree} — {item.field}</h3><p>{item.institute}</p><strong>CGPA: {item.cgpa}</strong><small>RELEVANT COURSEWORK</small><Tags items={item.courses} /></article>)}</div></section> }

function Publication() { return <section id="publications" className="section"><SectionIntro number="04" label="FEATURED PUBLICATION" title="Featured Research">Multimodal AI research for offensive meme detection and interpretable reasoning.</SectionIntro><article className="publication-card dsaa-card"><div className="dsaa-copy"><span className="accepted"><i /> IEEE DSAA 2026 — ACCEPTED</span><h3>A Multimodal LLM-Based Detection and Reasoning Framework for Deciphering Offensive Memes on Social Media Platform</h3><p className="publication-authors"><b>Abhishek Singh</b> · Omkeshwar · Naveen Saini · Nikhilanand Arya</p><small className="conference-name">IEEE International Conference on Data Science and Advanced Analytics</small><p>This work presents a multimodal LLM-based framework for detecting and reasoning about offensive memes by combining visual information with text extracted from social media memes.</p><Tags items={['Multimodal AI', 'Vision-Language Models', 'LLM Reasoning', 'Content Moderation']} /><span className="publication-status">◉&nbsp; Status: Accepted · DOI and proceedings link will be added upon publication</span></div><div className="dsaa-framework"><p>DETECTION &amp; REASONING FRAMEWORK</p><div className="framework-stages"><div><span><Eye /></span><b>IMAGE</b><small>Visual meme<br />content</small></div><i>+</i><div><span><MessageSquareText /></span><b>TEXT</b><small>OCR-extracted<br />caption</small></div><i>+</i><div><span><Network /></span><b>REASONING</b><small>LLM rationale<br />graph</small></div></div><div className="framework-footer">meme pixels ⊕ extracted text → multimodal LLM → verdict + explanation</div></div></article></section> }

function ProjectCard({ project }: { project: typeof projects[number] }) { const [open, setOpen] = useState(project.featured); return <article className={`project-card ${project.featured ? 'project-featured' : ''}`}>{project.featured && <span className="featured-label">FEATURED PROJECT</span>}<div className="project-number">{project.id}</div><p className="project-name">{project.name}</p><h3>{project.title}</h3><Tags items={project.technologies} /><p>{project.description}</p>{project.featured && <div className="project-metrics"><span><b>↗ +8.4% F1</b>Level-1 classification improvement</span><span><b>+5.3% F1</b>Level-2 classification improvement</span><span><b>32%</b>Inference-time reduction</span></div>}{project.pipeline.length > 0 && <div className="project-flow">{project.pipeline.map((step, i) => <span key={step}>{step}{i < project.pipeline.length - 1 && <ArrowRight />}</span>)}</div>}<button onClick={() => setOpen(!open)} className="details-toggle">{open ? 'Hide technical details' : 'Technical details'} <ChevronDown className={open ? 'flip' : ''} /></button><AnimatePresence>{open && <motion.ul className="project-details" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }}>{project.highlights.map(item => <li key={item}><Check />{item}</li>)}</motion.ul>}</AnimatePresence></article> }
function Projects() { return <section id="projects" className="section"><SectionIntro number="05" label="SELECTED PROJECTS" title="Applied Research Systems">Selected systems for multimodal detection, healthcare QA and retrieval-augmented generation.</SectionIntro><div className="projects-grid">{projects.map(project => <ProjectCard key={project.id} project={project} />)}</div></section> }

const skillCards = [
  ['Programming & Tools', ['Python', 'C/C++', 'SQL', 'Jupyter Notebook', 'Kaggle Notebook'], Code2],
  ['LLM / Generative AI', ['Generative Adversarial Networks', 'LangChain', 'Retrieval-Augmented Generation', 'Vision-Language Models', 'Large Language Models'], Sparkles],
  ['Machine Learning / Deep Learning', ['CNN', 'RNN', 'LSTM', 'GRU', 'Transformers', 'Transfer Learning', '3D Reconstruction', 'Neural Rendering'], BrainCircuit],
  ['Libraries & Frameworks', ['PyTorch', 'TensorFlow', 'Keras', 'Scikit-learn', 'Hugging Face', 'Pandas', 'NumPy', 'Hadoop'], Atom],
]
function Skills() { return <section id="skills" className="section"><SectionIntro number="06" label="TECHNICAL SKILLS" title="Technical Skills">A research engineer’s toolkit — organized by discipline, not by inflated percentages.</SectionIntro><div className="skills-grid skill-cards">{skillCards.map(([title, items, Icon]) => { const IconComponent = Icon as typeof Code2; return <article key={title as string}><span className="skill-icon"><IconComponent /></span><h3>{title as string}</h3><Tags items={items as string[]} /></article> })}</div></section> }
function ResearchExtras() { return <section className="section research-extras"><div><SectionIntro number="07" label="RESEARCH INTERESTS" title="Research Interests" /><div className="interest-tags">{researchInterests.map(item => <span key={item}><i />{item}</span>)}</div></div><div><SectionIntro number="08" label="CERTIFICATIONS" title="Certifications" /><div className="cert-list">{certifications.map(([name, source]) => <article key={name}><span><Atom /></span><div><b>{name}</b><small>{source}</small></div></article>)}</div></div></section> }
function AcademicService() { return <section className="section service"><SectionIntro number="08" label="ACADEMIC SERVICE" title="Research Community" /><article><BookOpen /><div><span className="accepted">TPC MEMBER · MMM 2027</span><h3>Technical Program Committee Member</h3><p>International Conference on Multimedia Modeling (MMM 2027)</p><small>Contributing to the academic research and peer-review community in multimedia and related areas.</small></div></article><div className="cert-row">{certifications.map(([name, source]) => <span key={name}><Atom /> <b>{name}</b> · {source}</span>)}</div></section> }

function Contact() { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard?.writeText(personalInfo.email); setCopied(true); setTimeout(() => setCopied(false), 1600) }; const items = [[Mail, 'EMAIL', personalInfo.email, `mailto:${personalInfo.email}`], [Phone, 'PHONE', personalInfo.phone, `tel:${personalInfo.phone.replace(/-/g, '')}`], [MapPin, 'LOCATION', personalInfo.location, ''], [Link2, 'LINKEDIN', 'abhishek-singh-546a7116a', personalInfo.linkedinUrl]]; return <section id="contact" className="section contact"><SectionIntro number="10" label="CONTACT" title="Let’s Build Intelligent Systems">I am open to research collaborations, AI/ML research opportunities, internships, and conversations around multimodal AI, deep learning, and generative AI.</SectionIntro><div className="contact-layout"><div className="contact-cards">{items.map(([Icon, label, value, href]) => { const IconComponent = Icon as typeof Mail; const contents = <><span><IconComponent /></span><div><small>{label as string}</small><b>{value as string}</b></div></>; return href ? <a className="contact-card" href={href as string} target={label === 'LINKEDIN' ? '_blank' : undefined} rel="noreferrer" key={label as string}>{contents}</a> : <div className="contact-card" key={label as string}>{contents}</div> })}</div><aside className="contact-cta"><p>OPEN TO OPPORTUNITIES</p><h3>Research collaborations, fellowships &amp; AI/ML roles.</h3><span>The fastest way to reach me is email — I usually respond within a day.</span><a className="button fill" href={`mailto:${personalInfo.email}`}>Get In Touch <ArrowUpRight /></a><button onClick={copy} className="copy-email">{copied ? <Check /> : <Copy />}{copied ? 'Email copied' : 'Copy email address'}</button></aside></div></section> }

function Footer() { return <footer><div><b>Abhishek<span>.</span>Singh</b><p>Deep Learning &amp; Multimodal AI Researcher</p></div><p>© 2026 · Prayagraj, India</p><a href="#home" aria-label="Back to top"><ArrowDown /></a></footer> }
export default function App() { return <><Navbar /><main><Hero /><ResearchTicker /><ResearchFocus /><Experience /><Education /><Publication /><Projects /><Skills /><ResearchExtras /><AcademicService /><Contact /></main><Footer /></> }
